### ISSUE TITLE
TypeError thrown while running npm start

### ISSUE THREAD

**Issue by CyberFlameGO** [Karl0497/WhatIsLife#3]
`TypeError: Cannot read property 'flags' of undefined` was thrown when I ran `npm start` however `localhost:3000` was opened in my browser and I did see the site.
I screenshotted my terminal here:
<img width="912" alt="Screen Shot 2021-05-17 at 10 24 37 AM" src="https://user-images.githubusercontent.com/24910512/118414664-1710fa80-b6fa-11eb-91c3-4e0034c5dcf3.png">
Here's a recording:
https://user-images.githubusercontent.com/24910512/118415979-89d1a400-b701-11eb-881d-71eab50e355c.mov

**Comment by KhoaNguyen0497** [comment]
I think typescript is not properly installed. Not sure what I did but I also installed it globally and locally

**Comment by CyberFlameGO** [comment]
I just installed it globally. I'll try locally installing it

**Comment by CyberFlameGO** [comment]
Same error even when both locally and globally installed

**Comment by KhoaNguyen0497** [comment]
npm install --save-dev typescript@rc

i fixed it by running this, can you try?

**Comment by CyberFlameGO** [comment]
Yep, that worked! Thank you!
